name: a320_instructor
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  auto_size_text: 3.0.0
  cached_network_image: 3.4.1
  file_picker: 10.1.9
  flutter_animate: 4.5.0
  flutter_tts: ^4.0.2
  font_awesome_flutter: ^10.8.0
  google_fonts: ^8.1.0
  google_mobile_ads: 6.0.0
  intl: 0.20.2
  page_transition: 2.2.1
  provider: 6.1.5
  url_launcher: 6.3.1
  uuid: ^4.0.0
  webview_flutter: 4.13.0
  webviewx_plus: 
    git:
      url: https://github.com/FlutterFlow/webviewx_plus.git
      ref: 4f84ece5e06d52643c5d844f41880baf8440c584
  cupertino_icons: ^1.0.0

dependency_overrides:
  font_awesome_flutter: 10.8.0
  page_transition: 2.2.1
  http: 1.4.0
  uuid: 4.0.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
